sperma

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -29,6 +29,9 @@ jobs:
       - name: List build directory
         run: ls -R app/build/outputs/apk/release/
 
+      - name: Check if APK exists
+        run: if [ ! -f app/build/outputs/apk/release/app-release.apk ]; then echo "APK not found!"; exit 1; fi
+
       - name: Upload APK
         uses: actions/upload-artifact@v2
         with:
@@ -62,6 +65,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: app/build/outputs/apk/release/app-release.apk
+          asset_path: app-release.apk
           asset_name: app-release.apk
           asset_content_type: application/vnd.android.package-archive
