sperma

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -30,13 +30,13 @@ jobs:
         run: ls -R app/build/outputs/apk/release/
 
       - name: Check if APK exists
-        run: if [ ! -f app/build/outputs/apk/release/app-release.apk ]; then echo "APK not found!"; exit 1; fi
+        run: if [ ! -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then echo "APK not found!"; exit 1; fi
 
       - name: Upload APK
         uses: actions/upload-artifact@v2
         with:
-          name: app-release-apk
-          path: app/build/outputs/apk/release/app-release.apk
+          name: app-release-unsigned.apk
+          path: app/build/outputs/apk/release/app-release-unsigned.apk
 
   release:
     needs: build
