sperma

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -2,8 +2,8 @@ name: Android CI
 
 on:
   push:
-    branches:
-      - 'master'  # Триггер на пуш в ветку master
+    tags:
+      - 'v*.*.*'  # Триггер на пуш тегов, например v1.0.0
   workflow_dispatch:
 
 jobs:
@@ -24,19 +24,19 @@ jobs:
         run: chmod +x ./gradlew
 
       - name: Build with Gradle
-        run: ./gradlew assembleDebug
+        run: ./gradlew assembleRelease
 
       - name: List build directory
-        run: ls -R app/build/outputs/apk/debug/
+        run: ls -R app/build/outputs/apk/release/
 
       - name: Check if APK exists
-        run: if [ ! -f app/build/outputs/apk/debug/app-debug.apk ]; then echo "APK not found!"; exit 1; fi
+        run: if [ ! -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then echo "APK not found!"; exit 1; fi
 
       - name: Upload APK
         uses: actions/upload-artifact@v2
         with:
-          name: app-debug.apk
-          path: app/build/outputs/apk/debug/app-debug.apk
+          name: app-release-unsigned.apk
+          path: app/build/outputs/apk/release/app-release-unsigned.apk
 
   release:
     needs: build
@@ -45,14 +45,14 @@ jobs:
       - name: Download APK
         uses: actions/download-artifact@v2
         with:
-          name: app-debug.apk
+          name: app-release-unsigned.apk
           path: .
 
       - name: List files in current directory
         run: ls -al
 
       - name: Check if downloaded APK exists
-        run: if [ ! -f ./app-debug.apk ]; then echo "Downloaded APK not found!"; exit 1; fi
+        run: if [ ! -f ./app-release-unsigned.apk ]; then echo "Downloaded APK not found!"; exit 1; fi
 
       - name: Create Release
         id: create_release
@@ -71,6 +71,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.PAT }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./app-debug.apk
-          asset_name: app-debug.apk
+          asset_path: ./app-release-unsigned.apk
+          asset_name: app-release-unsigned.apk
           asset_content_type: application/vnd.android.package-archive
