sperma

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -20,23 +20,26 @@ jobs:
           distribution: 'zulu'
           java-version: '17'
 
+      - name: Decode keystore
+        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
+
       - name: Grant execute permission for gradlew
         run: chmod +x ./gradlew
 
       - name: Build with Gradle
-        run: ./gradlew assembleRelease
+        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=release.keystore -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
 
       - name: List build directory
         run: ls -R app/build/outputs/apk/release/
 
       - name: Check if APK exists
-        run: if [ ! -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then echo "APK not found!"; exit 1; fi
+        run: if [ ! -f app/build/outputs/apk/release/app-release.apk ]; then echo "APK not found!"; exit 1; fi
 
       - name: Upload APK
         uses: actions/upload-artifact@v2
         with:
-          name: app-release-unsigned.apk
-          path: app/build/outputs/apk/release/app-release-unsigned.apk
+          name: app-release.apk
+          path: app/build/outputs/apk/release/app-release.apk
 
   release:
     needs: build
@@ -45,14 +48,14 @@ jobs:
       - name: Download APK
         uses: actions/download-artifact@v2
         with:
-          name: app-release-unsigned.apk
+          name: app-release.apk
           path: .
 
       - name: List files in current directory
         run: ls -al
 
       - name: Check if downloaded APK exists
-        run: if [ ! -f ./app-release-unsigned.apk ]; then echo "Downloaded APK not found!"; exit 1; fi
+        run: if [ ! -f ./app-release.apk ]; then echo "Downloaded APK not found!"; exit 1; fi
 
       - name: Create Release
         id: create_release
@@ -71,6 +74,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.PAT }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./app-release-unsigned.apk
-          asset_name: app-release-unsigned.apk
+          asset_path: ./app-release.apk
+          asset_name: app-release.apk
           asset_content_type: application/vnd.android.package-archive
